//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOANTOTNGHIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetails
    {
        public int Id { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public string Description { get; set; }
        public Nullable<int> Floor { get; set; }
        public string Sanitary { get; set; }
        public Nullable<int> PeopleNum { get; set; }
        public Nullable<double> PriceElectric { get; set; }
        public Nullable<double> PriceWater { get; set; }
        public Nullable<int> BedRoomNumber { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
