//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOANTOTNGHIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Street
    {
        public Street()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdDistrict { get; set; }
    
        public virtual District District { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
