//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOANTOTNGHIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<double> IsAction { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public Nullable<int> IdUser { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual User User { get; set; }
    }
}
