//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOANTOTNGHIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Transaction = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string LoginId { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Avatar { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual ICollection<Transaction> Transaction { get; set; }
    }
}
